
name: Copy Files to Azure Storage

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  upload-to-storage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        run: |
          echo "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" > ~/.azure/connection_string

      - name: Change Directory
        run: |
          cd y/
          echo "Current working directory is: $(pwd)"

      - name: Upload files to Azure Storage
        run: |
          az storage blob upload-batch \
            --connection-string "$(cat ~/.azure/connection_string)" \
            --source path/ \
            --destination containerx \
            --pattern "*"

        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
