name: Copy Files to Azure Storage

on:
  push:
    branches:
      - main  # Ou o branch de sua preferência
  workflow_dispatch:

jobs:
  upload-to-storage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Criar diretório ~/.azure e configurar o Azure CLI
      - name: Configure Azure CLI
        run: |
          mkdir -p ~/.azure
          echo "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" > ~/.azure/connection_string

      # Step 3: Instalar a CLI do Azure (se não estiver instalada)
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Step 4: Entrar na pasta 'y/' e realizar o upload
      - name: Upload files to Azure Storage
        run: |
          az storage blob upload-batch \
            --connection-string "$(cat ~/.azure/connection_string)" \
            --source path/ \
            --destination containerx \
            --pattern "*"

        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
